// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz8q9dz3pSDkKPofgoaiNke2qL6D-iReg',
    appId: '1:337219684011:web:f777b66533ac503c2599ee',
    messagingSenderId: '337219684011',
    projectId: 'notes-todo-bb9b5',
    authDomain: 'notes-todo-bb9b5.firebaseapp.com',
    databaseURL: 'https://notes-todo-bb9b5-default-rtdb.firebaseio.com',
    storageBucket: 'notes-todo-bb9b5.firebasestorage.app',
    measurementId: 'G-PJX5PX72QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxQn-KRifJeMe32_tuy_aM28DI4Yw-wE4',
    appId: '1:337219684011:android:36dd737163cb0ebe2599ee',
    messagingSenderId: '337219684011',
    projectId: 'notes-todo-bb9b5',
    databaseURL: 'https://notes-todo-bb9b5-default-rtdb.firebaseio.com',
    storageBucket: 'notes-todo-bb9b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcYvgGUQZJ8YEqvfYmX6p7_7_BpE0gWiU',
    appId: '1:337219684011:ios:e58dbf7686cbce782599ee',
    messagingSenderId: '337219684011',
    projectId: 'notes-todo-bb9b5',
    databaseURL: 'https://notes-todo-bb9b5-default-rtdb.firebaseio.com',
    storageBucket: 'notes-todo-bb9b5.firebasestorage.app',
    iosBundleId: 'com.example.notesTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcYvgGUQZJ8YEqvfYmX6p7_7_BpE0gWiU',
    appId: '1:337219684011:ios:e58dbf7686cbce782599ee',
    messagingSenderId: '337219684011',
    projectId: 'notes-todo-bb9b5',
    databaseURL: 'https://notes-todo-bb9b5-default-rtdb.firebaseio.com',
    storageBucket: 'notes-todo-bb9b5.firebasestorage.app',
    iosBundleId: 'com.example.notesTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz8q9dz3pSDkKPofgoaiNke2qL6D-iReg',
    appId: '1:337219684011:web:3bbc2d9361b4d38f2599ee',
    messagingSenderId: '337219684011',
    projectId: 'notes-todo-bb9b5',
    authDomain: 'notes-todo-bb9b5.firebaseapp.com',
    databaseURL: 'https://notes-todo-bb9b5-default-rtdb.firebaseio.com',
    storageBucket: 'notes-todo-bb9b5.firebasestorage.app',
    measurementId: 'G-TPM9E20ZS4',
  );
}
